# Generated by Django 2.1.4 on 2018-12-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('rut_tecnico', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email_tecnico', models.CharField(blank=True, max_length=30)),
                ('nombre_tecnico', models.CharField(max_length=30)),
                ('apellido_tecnico', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
