# Generated by Django 2.1.4 on 2018-12-09 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0002_auto_20181209_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, max_length=30)),
                ('apellidos_cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('comuna_cliente', models.CharField(max_length=30)),
                ('telefono_cliente', models.IntegerField(blank=True, null=True)),
                ('correo_cliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('n_folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_folio', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('hora_inicio_folio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_termino_folio', models.TimeField()),
                ('codigo_ascensor', models.CharField(max_length=30)),
                ('fallas_detectadas_folio', models.TextField(max_length=150)),
                ('reparaciones_efectuadas_folio', models.TextField(max_length=150)),
                ('piezas_cambiadas_folio', models.TextField(max_length=150)),
                ('cliente_folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosnecsa.Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='email_tecnico',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='folio',
            name='receptor_trabajo_folio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rosnecsa.Tecnico'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='cliente',
            field=models.ManyToManyField(blank=True, null=True, to='rosnecsa.Cliente'),
        ),
    ]
