# Generated by Django 2.1.4 on 2018-12-09 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0003_auto_20181209_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='fecha_folio',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
