# Generated by Django 2.1.4 on 2018-12-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0004_auto_20181209_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa_tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_empleado', models.EmailField(max_length=30)),
            ],
        ),
    ]
