# Generated by Django 2.1.4 on 2018-12-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0005_empresa_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='cliente',
            field=models.ManyToManyField(blank=True, to='rosnecsa.Cliente'),
        ),
    ]
