# Generated by Django 2.1.4 on 2018-12-13 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0006_auto_20181212_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='hora_inicio_folio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='%H:%M'),
        ),
        migrations.AlterField(
            model_name='folio',
            name='hora_termino_folio',
            field=models.TimeField(verbose_name='%H:%M'),
        ),
    ]
