# Generated by Django 2.1.4 on 2018-12-13 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0007_auto_20181213_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo_cliente',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='folio',
            name='hora_inicio_folio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='folio',
            name='hora_termino_folio',
            field=models.TimeField(),
        ),
    ]
