# Generated by Django 2.1.4 on 2018-12-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosnecsa', '0009_auto_20181213_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folio',
            name='fallas_detectadas_folio',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
